-- =====================================================================
-- ANO_TURMA_2025_MODELO_RELACIONAL.sql
-- Modelo Físico Oracle (corrigido, sem UNKNOWN)
-- =====================================================================

-- Usuário
CREATE TABLE tb_usuario (
    id            NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nome          VARCHAR2(100)       NOT NULL,
    email         VARCHAR2(150)       NOT NULL,
    senha_hash    VARCHAR2(255)       NOT NULL,
    perfil        VARCHAR2(20)        NOT NULL,
    status        VARCHAR2(10)        NOT NULL,
    dt_criacao    TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT pk_tb_usuario PRIMARY KEY (id),
    CONSTRAINT uq_tb_usuario__email UNIQUE (email),
    CONSTRAINT ck_tb_usuario__perfil CHECK (perfil IN ('ADMIN','OPERADOR')),
    CONSTRAINT ck_tb_usuario__status CHECK (status IN ('ATIVO','INATIVO'))
);

-- Categoria
CREATE TABLE tb_categoria (
    id            NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nome          VARCHAR2(80)        NOT NULL,
    dt_criacao    TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT pk_tb_categoria PRIMARY KEY (id),
    CONSTRAINT uq_tb_categoria__nome UNIQUE (nome)
);

-- Produto
CREATE TABLE tb_produto (
    id            NUMBER GENERATED BY DEFAULT AS IDENTITY,
    categoria_id  NUMBER              NOT NULL,
    nome          VARCHAR2(120)       NOT NULL,
    sku           VARCHAR2(40)        NOT NULL,
    preco         NUMBER(12,2)        NOT NULL,
    estoque       NUMBER(10) DEFAULT 0 NOT NULL,
    ativo         CHAR(1) DEFAULT 'S' NOT NULL,
    dt_criacao    TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT pk_tb_produto PRIMARY KEY (id),
    CONSTRAINT fk_tb_produto__tb_categoria FOREIGN KEY (categoria_id)
        REFERENCES tb_categoria (id),
    CONSTRAINT uq_tb_produto__sku UNIQUE (sku),
    CONSTRAINT ck_tb_produto__preco CHECK (preco >= 0),
    CONSTRAINT ck_tb_produto__estoque CHECK (estoque >= 0),
    CONSTRAINT ck_tb_produto__ativo CHECK (ativo IN ('S','N'))
);

-- Cliente
CREATE TABLE tb_cliente (
    id            NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nome          VARCHAR2(120)       NOT NULL,
    email         VARCHAR2(150)       NOT NULL,
    cpf           VARCHAR2(11),
    telefone      VARCHAR2(20),
    dt_cadastro   TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT pk_tb_cliente PRIMARY KEY (id),
    CONSTRAINT uq_tb_cliente__email UNIQUE (email),
    CONSTRAINT uq_tb_cliente__cpf UNIQUE (cpf),
    CONSTRAINT ck_tb_cliente__cpf CHECK (cpf IS NULL OR REGEXP_LIKE(cpf, '^[0-9]{11}$'))
);

-- Endereço
CREATE TABLE tb_endereco (
    id            NUMBER GENERATED BY DEFAULT AS IDENTITY,
    cliente_id    NUMBER              NOT NULL,
    tipo          VARCHAR2(15)        NOT NULL,
    logradouro    VARCHAR2(120)       NOT NULL,
    numero        VARCHAR2(10)        NOT NULL,
    complemento   VARCHAR2(60),
    bairro        VARCHAR2(80)        NOT NULL,
    cidade        VARCHAR2(80)        NOT NULL,
    uf            CHAR(2)             NOT NULL,
    cep           VARCHAR2(8)         NOT NULL,
    CONSTRAINT pk_tb_endereco PRIMARY KEY (id),
    CONSTRAINT fk_tb_endereco__tb_cliente FOREIGN KEY (cliente_id)
        REFERENCES tb_cliente (id) ON DELETE CASCADE,
    CONSTRAINT ck_tb_endereco__tipo CHECK (tipo IN ('RESIDENCIAL','COMERCIAL')),
    CONSTRAINT ck_tb_endereco__uf CHECK (uf IN ('AC','AL','AP','AM','BA','CE','DF','ES','GO','MA','MT','MS','MG','PA','PB','PR','PE','PI','RJ','RN','RS','RO','RR','SC','SP','SE','TO')),
    CONSTRAINT ck_tb_endereco__cep CHECK (REGEXP_LIKE(cep, '^[0-9]{8}$'))
);

-- Pedido
CREATE TABLE tb_pedido (
    id            NUMBER GENERATED BY DEFAULT AS IDENTITY,
    cliente_id    NUMBER              NOT NULL,
    usuario_id    NUMBER,
    status        VARCHAR2(15)        NOT NULL,
    valor_total   NUMBER(12,2) DEFAULT 0 NOT NULL,
    dt_pedido     TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT pk_tb_pedido PRIMARY KEY (id),
    CONSTRAINT fk_tb_pedido__tb_cliente FOREIGN KEY (cliente_id)
        REFERENCES tb_cliente (id),
    CONSTRAINT fk_tb_pedido__tb_usuario FOREIGN KEY (usuario_id)
        REFERENCES tb_usuario (id),
    CONSTRAINT ck_tb_pedido__status CHECK (status IN ('ABERTO','PAGO','ENVIADO','CANCELADO')),
    CONSTRAINT ck_tb_pedido__valor_total CHECK (valor_total >= 0)
);

-- Pedido Item
CREATE TABLE tb_pedido_item (
    pedido_id     NUMBER NOT NULL,
    produto_id    NUMBER NOT NULL,
    quantidade    NUMBER(10) NOT NULL,
    preco_unitario NUMBER(12,2) NOT NULL,
    CONSTRAINT pk_tb_pedido_item PRIMARY KEY (pedido_id, produto_id),
    CONSTRAINT fk_tb_pedido_item__tb_pedido FOREIGN KEY (pedido_id)
        REFERENCES tb_pedido (id) ON DELETE CASCADE,
    CONSTRAINT fk_tb_pedido_item__tb_produto FOREIGN KEY (produto_id)
        REFERENCES tb_produto (id),
    CONSTRAINT ck_tb_pedido_item__quantidade CHECK (quantidade > 0),
    CONSTRAINT ck_tb_pedido_item__preco_unit CHECK (preco_unitario >= 0)
);

-- Pagamento
CREATE TABLE tb_pagamento (
    id            NUMBER GENERATED BY DEFAULT AS IDENTITY,
    pedido_id     NUMBER NOT NULL,
    forma         VARCHAR2(10) NOT NULL,
    valor         NUMBER(12,2) NOT NULL,
    status        VARCHAR2(12) NOT NULL,
    dt_pagamento  TIMESTAMP,
    CONSTRAINT pk_tb_pagamento PRIMARY KEY (id),
    CONSTRAINT fk_tb_pagamento__tb_pedido FOREIGN KEY (pedido_id)
        REFERENCES tb_pedido (id) ON DELETE CASCADE,
    CONSTRAINT uq_tb_pagamento__pedido UNIQUE (pedido_id),
    CONSTRAINT ck_tb_pagamento__forma CHECK (forma IN ('PIX','BOLETO','CARTAO')),
    CONSTRAINT ck_tb_pagamento__status CHECK (status IN ('PENDENTE','CONFIRMADO','NEGADO')),
    CONSTRAINT ck_tb_pagamento__valor CHECK (valor >= 0)
);
